export const growArray = [
    { rate: '140%', title: 'Qubit top customers annual growth rate.' },
    { rate: '$20bn', title: 'Online sales generated by our customers in 2020.' },
    { rate: '364', title: 'Ecommerce stores are growing faster with Qubit.' },
    { rate: '9.5m', title: 'Personalized experiences delivered every hour.' },
    { rate: '4.4m', title: 'Shoppers influenced by Qubit every day.' },
    { rate: '$1.6bn', title: 'Incremental revenue generated by our customers in 2020.*' },
]